export const FETCH_TRENDING_GIF_REQUEST = 'FETCH_TRENDING_GIF_REQUEST';
export const FETCH_TRENDING_GIF_SUCCESS = 'FETCH_TRENDING_GIF_SUCCESS';
export const FETCH_TRENDING_GIF_ERROR = 'FETCH_TRENDING_GIF_ERROR'; 

export const FETCH_GIF_BY_KEYWORD_REQUEST = 'FETCH_GIF_BY_KEYWORD_REQUEST';
export const FETCH_GIF_BY_KEYWORD_SUCCESS = 'FETCH_GIF_BY_KEYWORD_SUCCESS';
export const FETCH_GIF_BY_KEYWORD_ERROR = 'FETCH_GIF_BY_KEYWORD_ERROR'; 